112 ref add argument in torch trainer whether to predict or not
TeamEpochGithub/epochalyst pull request #120
Opened 2024-04-15 14:41 UTC by hjdeheer

# Adds partial prediction, based on flag ` all_predict` 

# Now also supports numpy arrays as indices

2024-04-15 15:00 UTC, schobbejak commented
Add pr information

2024-04-15 15:02 UTC, tolgakopar approved these changes
Looks good

2024-04-15 20:54 UTC, schobbejak requested changes

2024-04-15 20:54 UTC, schobbejak commented on epochalyst/pipeline/model/training/torch_trainer.py
>          concat_dataset: Dataset[Any] = self._concat_datasets(
Should be moved into the if statement otherwise its unnecessary

2024-04-16 14:46 UTC, schobbejak submitted a review, later dismissed

2024-04-16 15:20 UTC, schobbejak approved these changes
Looks fine

2024-04-16 15:20 UTC, merged